##
# Core configuration for BlueMap.
#
# BlueMap requires downloading Minecraft client resources to render the map.
# The download is governed by Mojang's EULA: https://account.mojang.com/documents/minecraft_eula
# Accepting here means you agree to those terms.
##

accept-download: true
